# Generated by Django 4.2.8 on 2023-12-08 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('created_from', models.CharField(max_length=100)),
                ('P_Name', models.CharField(max_length=200)),
                ('P_Gruppe', models.CharField(max_length=50)),
                ('P_ID', models.CharField(max_length=12)), 
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
